# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test_UI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'RxSwift', '6.1.0'
pod 'RxCocoa', '6.1.0'
pod 'SnapKit', '~> 5.0.0'
pod 'Localize-Swift', '~> 3.2'
pod 'NVActivityIndicatorView', '~> 4.8.0'
pod 'Reusable'
pod 'KeychainSwift', '~> 19.0'
pod "Apollo", '~> 0.26.0'
pod 'Action'
pod 'IQKeyboardManagerSwift'
pod 'NYTPhotoViewer'
  # Pods for test_UI

end
